// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/login.tsx";
import * as $2 from "./routes/logout.ts";
import * as $3 from "./routes/stars.tsx";
import * as $$0 from "./islands/loginRedirect.tsx";
import * as $$1 from "./islands/starsList.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/login.tsx": $1,
    "./routes/logout.ts": $2,
    "./routes/stars.tsx": $3,
  },
  islands: {
    "./islands/loginRedirect.tsx": $$0,
    "./islands/starsList.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
