[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  autoLaunch = false

[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200
